//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceConnexion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Classe", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class Classe : object
    {
        
        private string DescriptionField;
        
        private System.Collections.Generic.List<ServiceConnexion.Hero> HeroesField;
        
        private int IdField;
        
        private ServiceConnexion.Monde MondeField;
        
        private int MondeIdField;
        
        private string NomClasseField;
        
        private int StatBaseDexField;
        
        private int StatBaseIntField;
        
        private int StatBaseStrField;
        
        private int StatBaseVitaliteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.Hero> Heroes
        {
            get
            {
                return this.HeroesField;
            }
            set
            {
                this.HeroesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Monde Monde
        {
            get
            {
                return this.MondeField;
            }
            set
            {
                this.MondeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId
        {
            get
            {
                return this.MondeIdField;
            }
            set
            {
                this.MondeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomClasse
        {
            get
            {
                return this.NomClasseField;
            }
            set
            {
                this.NomClasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseDex
        {
            get
            {
                return this.StatBaseDexField;
            }
            set
            {
                this.StatBaseDexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseInt
        {
            get
            {
                return this.StatBaseIntField;
            }
            set
            {
                this.StatBaseIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseStr
        {
            get
            {
                return this.StatBaseStrField;
            }
            set
            {
                this.StatBaseStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseVitalite
        {
            get
            {
                return this.StatBaseVitaliteField;
            }
            set
            {
                this.StatBaseVitaliteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Monde", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class Monde : object
    {
        
        private System.Collections.Generic.List<ServiceConnexion.Classe> ClassesField;
        
        private string DescriptionField;
        
        private System.Collections.Generic.List<ServiceConnexion.Hero> HeroesField;
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceConnexion.Item> ItemsField;
        
        private int LimiteXField;
        
        private int LimiteYField;
        
        private System.Collections.Generic.List<ServiceConnexion.Monstre> MonstresField;
        
        private System.Collections.Generic.List<ServiceConnexion.ObjetMonde> ObjetMondesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.Classe> Classes
        {
            get
            {
                return this.ClassesField;
            }
            set
            {
                this.ClassesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.Hero> Heroes
        {
            get
            {
                return this.HeroesField;
            }
            set
            {
                this.HeroesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.Item> Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimiteX
        {
            get
            {
                return this.LimiteXField;
            }
            set
            {
                this.LimiteXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimiteY
        {
            get
            {
                return this.LimiteYField;
            }
            set
            {
                this.LimiteYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.Monstre> Monstres
        {
            get
            {
                return this.MonstresField;
            }
            set
            {
                this.MonstresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.ObjetMonde> ObjetMondes
        {
            get
            {
                return this.ObjetMondesField;
            }
            set
            {
                this.ObjetMondesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hero", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class Hero : object
    {
        
        private ServiceConnexion.Classe ClasseField;
        
        private int ClasseIdField;
        
        private ServiceConnexion.CompteJoueur CompteJoueurField;
        
        private int CompteJoueurIdField;
        
        private bool EstConnecteField;
        
        private long ExperienceField;
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceConnexion.InventaireHero> InventaireHeroesField;
        
        private System.Collections.Generic.List<ServiceConnexion.Item> ItemsField;
        
        private ServiceConnexion.Monde MondeField;
        
        private int MondeIdField;
        
        private int NiveauField;
        
        private string NomHeroField;
        
        private int StatDexField;
        
        private int StatIntField;
        
        private int StatStrField;
        
        private int StatVitaliteField;
        
        private int XField;
        
        private int YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Classe Classe
        {
            get
            {
                return this.ClasseField;
            }
            set
            {
                this.ClasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClasseId
        {
            get
            {
                return this.ClasseIdField;
            }
            set
            {
                this.ClasseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.CompteJoueur CompteJoueur
        {
            get
            {
                return this.CompteJoueurField;
            }
            set
            {
                this.CompteJoueurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompteJoueurId
        {
            get
            {
                return this.CompteJoueurIdField;
            }
            set
            {
                this.CompteJoueurIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstConnecte
        {
            get
            {
                return this.EstConnecteField;
            }
            set
            {
                this.EstConnecteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Experience
        {
            get
            {
                return this.ExperienceField;
            }
            set
            {
                this.ExperienceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.InventaireHero> InventaireHeroes
        {
            get
            {
                return this.InventaireHeroesField;
            }
            set
            {
                this.InventaireHeroesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.Item> Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Monde Monde
        {
            get
            {
                return this.MondeField;
            }
            set
            {
                this.MondeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId
        {
            get
            {
                return this.MondeIdField;
            }
            set
            {
                this.MondeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Niveau
        {
            get
            {
                return this.NiveauField;
            }
            set
            {
                this.NiveauField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomHero
        {
            get
            {
                return this.NomHeroField;
            }
            set
            {
                this.NomHeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatDex
        {
            get
            {
                return this.StatDexField;
            }
            set
            {
                this.StatDexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatInt
        {
            get
            {
                return this.StatIntField;
            }
            set
            {
                this.StatIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatStr
        {
            get
            {
                return this.StatStrField;
            }
            set
            {
                this.StatStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatVitalite
        {
            get
            {
                return this.StatVitaliteField;
            }
            set
            {
                this.StatVitaliteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompteJoueur", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class CompteJoueur : object
    {
        
        private string CourrielField;
        
        private System.Collections.Generic.List<ServiceConnexion.Hero> HeroesField;
        
        private int IdField;
        
        private byte[] MotDePasseHashField;
        
        private string NomField;
        
        private string NomJoueurField;
        
        private string PrenomField;
        
        private System.Guid SaltField;
        
        private int TypeUtilisateurField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Courriel
        {
            get
            {
                return this.CourrielField;
            }
            set
            {
                this.CourrielField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.Hero> Heroes
        {
            get
            {
                return this.HeroesField;
            }
            set
            {
                this.HeroesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MotDePasseHash
        {
            get
            {
                return this.MotDePasseHashField;
            }
            set
            {
                this.MotDePasseHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomJoueur
        {
            get
            {
                return this.NomJoueurField;
            }
            set
            {
                this.NomJoueurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom
        {
            get
            {
                return this.PrenomField;
            }
            set
            {
                this.PrenomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Salt
        {
            get
            {
                return this.SaltField;
            }
            set
            {
                this.SaltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeUtilisateur
        {
            get
            {
                return this.TypeUtilisateurField;
            }
            set
            {
                this.TypeUtilisateurField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventaireHero", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class InventaireHero : object
    {
        
        private int IdHeroField;
        
        private ServiceConnexion.Hero IdHeroNavigationField;
        
        private int IdInventaireHeroField;
        
        private ServiceConnexion.Item ItemField;
        
        private int ItemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHero
        {
            get
            {
                return this.IdHeroField;
            }
            set
            {
                this.IdHeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Hero IdHeroNavigation
        {
            get
            {
                return this.IdHeroNavigationField;
            }
            set
            {
                this.IdHeroNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInventaireHero
        {
            get
            {
                return this.IdInventaireHeroField;
            }
            set
            {
                this.IdInventaireHeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Item Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class Item : object
    {
        
        private string DescriptionField;
        
        private System.Collections.Generic.List<ServiceConnexion.EffetItem> EffetItemsField;
        
        private int IdField;
        
        private System.Nullable<int> IdHeroField;
        
        private ServiceConnexion.Hero IdHeroNavigationField;
        
        private System.Nullable<int> ImageIdField;
        
        private System.Collections.Generic.List<ServiceConnexion.InventaireHero> InventaireHeroesField;
        
        private ServiceConnexion.Monde MondeField;
        
        private int MondeIdField;
        
        private string NomField;
        
        private System.Nullable<int> XField;
        
        private System.Nullable<int> YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.EffetItem> EffetItems
        {
            get
            {
                return this.EffetItemsField;
            }
            set
            {
                this.EffetItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdHero
        {
            get
            {
                return this.IdHeroField;
            }
            set
            {
                this.IdHeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Hero IdHeroNavigation
        {
            get
            {
                return this.IdHeroNavigationField;
            }
            set
            {
                this.IdHeroNavigationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageId
        {
            get
            {
                return this.ImageIdField;
            }
            set
            {
                this.ImageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceConnexion.InventaireHero> InventaireHeroes
        {
            get
            {
                return this.InventaireHeroesField;
            }
            set
            {
                this.InventaireHeroesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Monde Monde
        {
            get
            {
                return this.MondeField;
            }
            set
            {
                this.MondeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId
        {
            get
            {
                return this.MondeIdField;
            }
            set
            {
                this.MondeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EffetItem", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class EffetItem : object
    {
        
        private int IdField;
        
        private ServiceConnexion.Item ItemField;
        
        private int ItemIdField;
        
        private int TypeEffetField;
        
        private int ValeurEffetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Item Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeEffet
        {
            get
            {
                return this.TypeEffetField;
            }
            set
            {
                this.TypeEffetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValeurEffet
        {
            get
            {
                return this.ValeurEffetField;
            }
            set
            {
                this.ValeurEffetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Monstre", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class Monstre : object
    {
        
        private int IdField;
        
        private System.Nullable<int> ImageIdField;
        
        private ServiceConnexion.Monde MondeField;
        
        private int MondeIdField;
        
        private int NiveauField;
        
        private string NomField;
        
        private float StatDmgMaxField;
        
        private float StatDmgMinField;
        
        private int StatPvField;
        
        private int XField;
        
        private int YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageId
        {
            get
            {
                return this.ImageIdField;
            }
            set
            {
                this.ImageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Monde Monde
        {
            get
            {
                return this.MondeField;
            }
            set
            {
                this.MondeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId
        {
            get
            {
                return this.MondeIdField;
            }
            set
            {
                this.MondeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Niveau
        {
            get
            {
                return this.NiveauField;
            }
            set
            {
                this.NiveauField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float StatDmgMax
        {
            get
            {
                return this.StatDmgMaxField;
            }
            set
            {
                this.StatDmgMaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float StatDmgMin
        {
            get
            {
                return this.StatDmgMinField;
            }
            set
            {
                this.StatDmgMinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatPv
        {
            get
            {
                return this.StatPvField;
            }
            set
            {
                this.StatPvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjetMonde", Namespace="http://schemas.datacontract.org/2004/07/TP1.EF")]
    public partial class ObjetMonde : object
    {
        
        private string DescriptionField;
        
        private int IdField;
        
        private ServiceConnexion.Monde MondeField;
        
        private int MondeIdField;
        
        private int TypeObjetField;
        
        private int XField;
        
        private int YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceConnexion.Monde Monde
        {
            get
            {
                return this.MondeField;
            }
            set
            {
                this.MondeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId
        {
            get
            {
                return this.MondeIdField;
            }
            set
            {
                this.MondeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeObjet
        {
            get
            {
                return this.TypeObjetField;
            }
            set
            {
                this.TypeObjetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceConnexion.IConnexion")]
    public interface IConnexion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/Login", ReplyAction="http://tempuri.org/IConnexion/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/Login", ReplyAction="http://tempuri.org/IConnexion/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/CreerHero", ReplyAction="http://tempuri.org/IConnexion/CreerHeroResponse")]
        void CreerHero(int str, int dex, int intel, int vit, int classeId, string nomHero, int mondeid, int joueurid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/CreerHero", ReplyAction="http://tempuri.org/IConnexion/CreerHeroResponse")]
        System.Threading.Tasks.Task CreerHeroAsync(int str, int dex, int intel, int vit, int classeId, string nomHero, int mondeid, int joueurid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerClassePourMonde", ReplyAction="http://tempuri.org/IConnexion/ListerClassePourMondeResponse")]
        System.Collections.Generic.List<ServiceConnexion.Classe> ListerClassePourMonde(int mondeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerClassePourMonde", ReplyAction="http://tempuri.org/IConnexion/ListerClassePourMondeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Classe>> ListerClassePourMondeAsync(int mondeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/CreeClasse", ReplyAction="http://tempuri.org/IConnexion/CreeClasseResponse")]
        void CreeClasse(string nom, string description, int statStr, int statDex, int statInt, int statVit, int mondeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/CreeClasse", ReplyAction="http://tempuri.org/IConnexion/CreeClasseResponse")]
        System.Threading.Tasks.Task CreeClasseAsync(string nom, string description, int statStr, int statDex, int statInt, int statVit, int mondeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/TrouverID", ReplyAction="http://tempuri.org/IConnexion/TrouverIDResponse")]
        int TrouverID(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/TrouverID", ReplyAction="http://tempuri.org/IConnexion/TrouverIDResponse")]
        System.Threading.Tasks.Task<int> TrouverIDAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/TrouverObjetMonde", ReplyAction="http://tempuri.org/IConnexion/TrouverObjetMondeResponse")]
        ServiceConnexion.Monde TrouverObjetMonde(int monde_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/TrouverObjetMonde", ReplyAction="http://tempuri.org/IConnexion/TrouverObjetMondeResponse")]
        System.Threading.Tasks.Task<ServiceConnexion.Monde> TrouverObjetMondeAsync(int monde_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/VerifierSiAdmin", ReplyAction="http://tempuri.org/IConnexion/VerifierSiAdminResponse")]
        int VerifierSiAdmin(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/VerifierSiAdmin", ReplyAction="http://tempuri.org/IConnexion/VerifierSiAdminResponse")]
        System.Threading.Tasks.Task<int> VerifierSiAdminAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerMonde", ReplyAction="http://tempuri.org/IConnexion/ListerMondeResponse")]
        System.Collections.Generic.List<ServiceConnexion.Monde> ListerMonde();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerMonde", ReplyAction="http://tempuri.org/IConnexion/ListerMondeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Monde>> ListerMondeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerClasses", ReplyAction="http://tempuri.org/IConnexion/ListerClassesResponse")]
        System.Collections.Generic.List<ServiceConnexion.Classe> ListerClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerClasses", ReplyAction="http://tempuri.org/IConnexion/ListerClassesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Classe>> ListerClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerHeros", ReplyAction="http://tempuri.org/IConnexion/ListerHerosResponse")]
        System.Collections.Generic.List<ServiceConnexion.Hero> ListerHeros(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerHeros", ReplyAction="http://tempuri.org/IConnexion/ListerHerosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Hero>> ListerHerosAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/SupprimerHero", ReplyAction="http://tempuri.org/IConnexion/SupprimerHeroResponse")]
        void SupprimerHero(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/SupprimerHero", ReplyAction="http://tempuri.org/IConnexion/SupprimerHeroResponse")]
        System.Threading.Tasks.Task SupprimerHeroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/SupprimerClasse", ReplyAction="http://tempuri.org/IConnexion/SupprimerClasseResponse")]
        void SupprimerClasse(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/SupprimerClasse", ReplyAction="http://tempuri.org/IConnexion/SupprimerClasseResponse")]
        System.Threading.Tasks.Task SupprimerClasseAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierClasse", ReplyAction="http://tempuri.org/IConnexion/ModifierClasseResponse")]
        void ModifierClasse(int id, string nom, string description, int force, int dex, int intel, int vitalite, int mondeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierClasse", ReplyAction="http://tempuri.org/IConnexion/ModifierClasseResponse")]
        System.Threading.Tasks.Task ModifierClasseAsync(int id, string nom, string description, int force, int dex, int intel, int vitalite, int mondeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerObjetPourMonde", ReplyAction="http://tempuri.org/IConnexion/ListerObjetPourMondeResponse")]
        System.Collections.Generic.List<ServiceConnexion.ObjetMonde> ListerObjetPourMonde(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerObjetPourMonde", ReplyAction="http://tempuri.org/IConnexion/ListerObjetPourMondeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.ObjetMonde>> ListerObjetPourMondeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/RetournerHero", ReplyAction="http://tempuri.org/IConnexion/RetournerHeroResponse")]
        ServiceConnexion.Hero RetournerHero(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/RetournerHero", ReplyAction="http://tempuri.org/IConnexion/RetournerHeroResponse")]
        System.Threading.Tasks.Task<ServiceConnexion.Hero> RetournerHeroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierStatutHero", ReplyAction="http://tempuri.org/IConnexion/ModifierStatutHeroResponse")]
        void ModifierStatutHero(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierStatutHero", ReplyAction="http://tempuri.org/IConnexion/ModifierStatutHeroResponse")]
        System.Threading.Tasks.Task ModifierStatutHeroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierPositionHeroMonde", ReplyAction="http://tempuri.org/IConnexion/ModifierPositionHeroMondeResponse")]
        void ModifierPositionHeroMonde(int _hero_id, int _x, int _y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierPositionHeroMonde", ReplyAction="http://tempuri.org/IConnexion/ModifierPositionHeroMondeResponse")]
        System.Threading.Tasks.Task ModifierPositionHeroMondeAsync(int _hero_id, int _x, int _y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerItemsPourMonde", ReplyAction="http://tempuri.org/IConnexion/ListerItemsPourMondeResponse")]
        System.Collections.Generic.List<ServiceConnexion.Item> ListerItemsPourMonde(int monde_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerItemsPourMonde", ReplyAction="http://tempuri.org/IConnexion/ListerItemsPourMondeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Item>> ListerItemsPourMondeAsync(int monde_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierInventaireHero", ReplyAction="http://tempuri.org/IConnexion/ModifierInventaireHeroResponse")]
        void ModifierInventaireHero(int idmonde, int itemid, int heroid, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ModifierInventaireHero", ReplyAction="http://tempuri.org/IConnexion/ModifierInventaireHeroResponse")]
        System.Threading.Tasks.Task ModifierInventaireHeroAsync(int idmonde, int itemid, int heroid, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerInventaireHero", ReplyAction="http://tempuri.org/IConnexion/ListerInventaireHeroResponse")]
        System.Collections.Generic.List<ServiceConnexion.Item> ListerInventaireHero(int _heroid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerInventaireHero", ReplyAction="http://tempuri.org/IConnexion/ListerInventaireHeroResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Item>> ListerInventaireHeroAsync(int _heroid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerHeroConnecter", ReplyAction="http://tempuri.org/IConnexion/ListerHeroConnecterResponse")]
        System.Collections.Generic.List<ServiceConnexion.Hero> ListerHeroConnecter(int mondeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnexion/ListerHeroConnecter", ReplyAction="http://tempuri.org/IConnexion/ListerHeroConnecterResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Hero>> ListerHeroConnecterAsync(int mondeid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IConnexionChannel : ServiceConnexion.IConnexion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ConnexionClient : System.ServiceModel.ClientBase<ServiceConnexion.IConnexion>, ServiceConnexion.IConnexion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConnexionClient() : 
                base(ConnexionClient.GetDefaultBinding(), ConnexionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConnexion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnexionClient(EndpointConfiguration endpointConfiguration) : 
                base(ConnexionClient.GetBindingForEndpoint(endpointConfiguration), ConnexionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnexionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConnexionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnexionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConnexionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConnexionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool Login(string username, string password)
        {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password)
        {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void CreerHero(int str, int dex, int intel, int vit, int classeId, string nomHero, int mondeid, int joueurid)
        {
            base.Channel.CreerHero(str, dex, intel, vit, classeId, nomHero, mondeid, joueurid);
        }
        
        public System.Threading.Tasks.Task CreerHeroAsync(int str, int dex, int intel, int vit, int classeId, string nomHero, int mondeid, int joueurid)
        {
            return base.Channel.CreerHeroAsync(str, dex, intel, vit, classeId, nomHero, mondeid, joueurid);
        }
        
        public System.Collections.Generic.List<ServiceConnexion.Classe> ListerClassePourMonde(int mondeID)
        {
            return base.Channel.ListerClassePourMonde(mondeID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Classe>> ListerClassePourMondeAsync(int mondeID)
        {
            return base.Channel.ListerClassePourMondeAsync(mondeID);
        }
        
        public void CreeClasse(string nom, string description, int statStr, int statDex, int statInt, int statVit, int mondeId)
        {
            base.Channel.CreeClasse(nom, description, statStr, statDex, statInt, statVit, mondeId);
        }
        
        public System.Threading.Tasks.Task CreeClasseAsync(string nom, string description, int statStr, int statDex, int statInt, int statVit, int mondeId)
        {
            return base.Channel.CreeClasseAsync(nom, description, statStr, statDex, statInt, statVit, mondeId);
        }
        
        public int TrouverID(string username)
        {
            return base.Channel.TrouverID(username);
        }
        
        public System.Threading.Tasks.Task<int> TrouverIDAsync(string username)
        {
            return base.Channel.TrouverIDAsync(username);
        }
        
        public ServiceConnexion.Monde TrouverObjetMonde(int monde_id)
        {
            return base.Channel.TrouverObjetMonde(monde_id);
        }
        
        public System.Threading.Tasks.Task<ServiceConnexion.Monde> TrouverObjetMondeAsync(int monde_id)
        {
            return base.Channel.TrouverObjetMondeAsync(monde_id);
        }
        
        public int VerifierSiAdmin(string username)
        {
            return base.Channel.VerifierSiAdmin(username);
        }
        
        public System.Threading.Tasks.Task<int> VerifierSiAdminAsync(string username)
        {
            return base.Channel.VerifierSiAdminAsync(username);
        }
        
        public System.Collections.Generic.List<ServiceConnexion.Monde> ListerMonde()
        {
            return base.Channel.ListerMonde();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Monde>> ListerMondeAsync()
        {
            return base.Channel.ListerMondeAsync();
        }
        
        public System.Collections.Generic.List<ServiceConnexion.Classe> ListerClasses()
        {
            return base.Channel.ListerClasses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Classe>> ListerClassesAsync()
        {
            return base.Channel.ListerClassesAsync();
        }
        
        public System.Collections.Generic.List<ServiceConnexion.Hero> ListerHeros(int id)
        {
            return base.Channel.ListerHeros(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Hero>> ListerHerosAsync(int id)
        {
            return base.Channel.ListerHerosAsync(id);
        }
        
        public void SupprimerHero(int id)
        {
            base.Channel.SupprimerHero(id);
        }
        
        public System.Threading.Tasks.Task SupprimerHeroAsync(int id)
        {
            return base.Channel.SupprimerHeroAsync(id);
        }
        
        public void SupprimerClasse(int id)
        {
            base.Channel.SupprimerClasse(id);
        }
        
        public System.Threading.Tasks.Task SupprimerClasseAsync(int id)
        {
            return base.Channel.SupprimerClasseAsync(id);
        }
        
        public void ModifierClasse(int id, string nom, string description, int force, int dex, int intel, int vitalite, int mondeid)
        {
            base.Channel.ModifierClasse(id, nom, description, force, dex, intel, vitalite, mondeid);
        }
        
        public System.Threading.Tasks.Task ModifierClasseAsync(int id, string nom, string description, int force, int dex, int intel, int vitalite, int mondeid)
        {
            return base.Channel.ModifierClasseAsync(id, nom, description, force, dex, intel, vitalite, mondeid);
        }
        
        public System.Collections.Generic.List<ServiceConnexion.ObjetMonde> ListerObjetPourMonde(int id)
        {
            return base.Channel.ListerObjetPourMonde(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.ObjetMonde>> ListerObjetPourMondeAsync(int id)
        {
            return base.Channel.ListerObjetPourMondeAsync(id);
        }
        
        public ServiceConnexion.Hero RetournerHero(int id)
        {
            return base.Channel.RetournerHero(id);
        }
        
        public System.Threading.Tasks.Task<ServiceConnexion.Hero> RetournerHeroAsync(int id)
        {
            return base.Channel.RetournerHeroAsync(id);
        }
        
        public void ModifierStatutHero(int id)
        {
            base.Channel.ModifierStatutHero(id);
        }
        
        public System.Threading.Tasks.Task ModifierStatutHeroAsync(int id)
        {
            return base.Channel.ModifierStatutHeroAsync(id);
        }
        
        public void ModifierPositionHeroMonde(int _hero_id, int _x, int _y)
        {
            base.Channel.ModifierPositionHeroMonde(_hero_id, _x, _y);
        }
        
        public System.Threading.Tasks.Task ModifierPositionHeroMondeAsync(int _hero_id, int _x, int _y)
        {
            return base.Channel.ModifierPositionHeroMondeAsync(_hero_id, _x, _y);
        }
        
        public System.Collections.Generic.List<ServiceConnexion.Item> ListerItemsPourMonde(int monde_id)
        {
            return base.Channel.ListerItemsPourMonde(monde_id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Item>> ListerItemsPourMondeAsync(int monde_id)
        {
            return base.Channel.ListerItemsPourMondeAsync(monde_id);
        }
        
        public void ModifierInventaireHero(int idmonde, int itemid, int heroid, int x, int y)
        {
            base.Channel.ModifierInventaireHero(idmonde, itemid, heroid, x, y);
        }
        
        public System.Threading.Tasks.Task ModifierInventaireHeroAsync(int idmonde, int itemid, int heroid, int x, int y)
        {
            return base.Channel.ModifierInventaireHeroAsync(idmonde, itemid, heroid, x, y);
        }
        
        public System.Collections.Generic.List<ServiceConnexion.Item> ListerInventaireHero(int _heroid)
        {
            return base.Channel.ListerInventaireHero(_heroid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Item>> ListerInventaireHeroAsync(int _heroid)
        {
            return base.Channel.ListerInventaireHeroAsync(_heroid);
        }
        
        public System.Collections.Generic.List<ServiceConnexion.Hero> ListerHeroConnecter(int mondeid)
        {
            return base.Channel.ListerHeroConnecter(mondeid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceConnexion.Hero>> ListerHeroConnecterAsync(int mondeid)
        {
            return base.Channel.ListerHeroConnecterAsync(mondeid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConnexion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConnexion))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7068/Connexion.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConnexionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConnexion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConnexionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConnexion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConnexion,
        }
    }
}
